title: Wu'Log
name: "wufujian's Tech Blog"
author: wufujian
twitter_username: wufujian
baseurl: "/wu-log"
description: Document my learning notes.
profile_url: "http://wfjs.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..3
